---
title: "exRNA_disease_biomarkers_nb"
output: html_notebook
author:
- name: "Roman E. Reggiardo"
  affiliation: "UC Santa Cruz Dept. of Biomolecular Engineering"
  email: "rreggiar@ucsc.edu"
editor_options: 
  chunk_output_type: console
---
# nb_setup
```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 8, collapse = T)
knitr::opts_chunk$set(message = F)
# here::set_here('/home/rreggiar/')
here::here()
suppressPackageStartupMessages(library(tidyverse))
```

# global_init
## ggplot_theme
```{r}
library(ggplot2)
library(ggthemes)
base_size = 10

ggplot2::theme_set(ggthemes::theme_foundation(base_size = base_size,
                                              base_family = 'Helvetica') + 
                     theme(plot.title = element_blank(),
                           panel.background = element_rect(colour = NA),
                           plot.background = element_rect(colour = NA),
                           panel.border = element_rect(colour = NA), 
                           axis.line = element_line(), 
                           axis.line.x = NULL, 
                           axis.line.y = NULL, 
                           axis.text = element_text(size = rel(0.95)), 
                           axis.text.x = element_text(margin = 
                                                        margin(t = 0.8 * base_size/4)), 
                           axis.text.x.top = element_text(margin = 
                                                            margin(b = 0.8 * base_size/4), 
                                                          vjust = 0), 
                           axis.text.y = element_text(margin = 
                                                        margin(r = 0.5 * base_size/4), 
                                                      hjust = 1),
                           axis.text.y.right = element_text(margin = 
                                                              margin(l = 0.5 * base_size/4), 
                                                            hjust = 0), 
                           axis.ticks = element_line(), 
                           axis.ticks.length = unit(base_size/2.5, "pt"), axis.ticks.length.x = NULL, 
                           axis.ticks.length.x.top = NULL, axis.ticks.length.x.bottom = NULL, 
                           axis.ticks.length.y = NULL, axis.ticks.length.y.left = NULL, 
                           axis.ticks.length.y.right = NULL,
                           strip.text = element_text(size = rel(0.95), face = 'bold'),
                           strip.background = element_blank(),
                           legend.key.size= unit(0.08, "in"),
                           legend.spacing = unit(0, "in"),
                           legend.key = element_rect(colour = NA),
                           legend.title = element_text(face="italic"),
                           legend.text = element_text(face = 'bold'),
                           legend.justification = c("right", "top"),
                           legend.box.just = "right",
                           legend.margin = margin(6, 6, 6, 6),
                           plot.margin=margin(0.04,
                                              0.04,
                                              0.04,
                                              0.04,
                                              unit = "in"),
                           legend.box.spacing = unit(-0.02, 'in'),
                           panel.grid.major = element_blank(),
                           panel.grid.minor = element_blank()
                           )
                   )
```

## data_path_obj
```{r}
figure.dir <- here::here('manuscript/figures')
input_data.dir <- here::here('data/input_data')
output_data.dir <- here::here('data/output_data')
qc_data.dir <- here::here('data/output_data/rna_qc')
meta_data.dir <- here::here('data/meta_data')
reference.dir <- here::here('reference')
r_code.dir <- here::here('R')
```

## figure_export
```{r}
figure_single_column_width = unit(89, 'mm')
figure_double_column_with = unit(183, 'mm')
figure_depth = unit(247, 'mm')

# install.packages("import")

import::from(.directory = r_code.dir, .from = 'helper_analysisFunctions.R', save.manuscript.panel)
```

## analysis_const
```{r}
chr_order <- c('chr1', 'chr2', 'chr3', 
               'chr4', 'chr5', 'chr6', 
               'chr7', 'chr8', 'chr9',
               'chr10', 'chr11', 'chr12', 
               'chr13', 'chr14', 'chr15', 
               'chr16', 'chr17',
               'chr18', 'chr19', 'chr20', 
               'chr21', 'chr22', 'chrX', 'chrY')


gencode_ver <- 39

three_color_pal <- RColorBrewer::brewer.pal(n = 3, 'Dark2')
eight_color_pal <- RColorBrewer::brewer.pal(n = 8, 'Dark2')

RColorBrewer::display.brewer.pal(n = 8, 'Dark2')

identity_color_pal <- c('ctrl' = eight_color_pal[[8]],
                        'panc' = eight_color_pal[[3]],
                        'covid' = eight_color_pal[[5]])

```

## meta_data_construction
```{r}

## reference meta data
if (! file.exists(file.path(meta_data.dir, 'reference_meta_data_df.rds'))) {
  
  reference_meta_data <- tibble::lst()
  
  reference_meta_data$ucsc_rmsk_insert_info.df <- 
    readr::read_tsv(file.path(reference.dir, 'ucsc.rmsk.insert.info.txt'),
             col_names = c('gene', 'clade', 'family'))
  
  reference_meta_data$gencode_tx_to_gene.df <- 
    readr::read_csv(file.path(reference.dir, 
                              paste0('gencode.v', gencode_ver, '.tx.to.gene.csv')),
                    col_names = c('tx', 'gene')) %>% 
    tidyr::separate(tx, sep = '\\|', 
                    into = c('enst','ensg',NA,NA,'tx','gene','len','biotype'))
  
  reference_meta_data$gencode_tx_to_gene.df %>% 
    dplyr::select(-enst) %>% 
    dplyr::group_by(biotype) %>% 
    dplyr::tally() -> reference_meta_data$gencode_biotype_count.df
  
  reference_meta_data$gencode_tx_to_gene.df %>% 
    dplyr::select(gene,biotype) %>% 
    dplyr::group_by(gene) %>% 
    dplyr::filter(all(biotype == 'lncRNA')) %>% 
    dplyr::distinct() -> reference_meta_data$gencode_lncRNA_gene_names.df
  
  reference_meta_data$ucsc_rmsk_tx_to_gene.df <-  
    readr::read_csv(file.path(reference.dir, 
                              'ucsc.rmsk.insert.analysis.tx.to.gene.csv'),
                    col_names = c('insert', 'info', 'gene', 'len', 'biotype')) %>% 
    mutate(enst = insert, ensg = info, tx = insert) %>% 
    select(enst, ensg, tx, gene, len, biotype, -insert, -info)
  
  reference_meta_data$total_tx_to_gene.df <- 
    rbind(reference_meta_data$gencode_tx_to_gene.df,
          reference_meta_data$ucsc_rmsk_tx_to_gene.df)
  
  saveRDS(reference_meta_data, file.path(meta_data.dir, 'reference_meta_data_df.rds'))
  
} else {
  reference_meta_data <- readRDS(file.path(meta_data.dir, 'reference_meta_data_df.rds'))
}

## sample_meta_data
if (! file.exists(file.path(meta_data.dir, 'sample_meta_data_df.rds'))) {
  
  list.files(meta_data.dir, pattern = '*_meta_data.csv') -> meta_file.list
  names(meta_file.list) <- meta_file.list
  
  meta_file.list %>% 
    purrr::imap(function(name, file) {
      readr::read_csv(file.path(meta_data.dir, file))
    }) -> sample_meta_data
  
  saveRDS(sample_meta_data, file.path(meta_data.dir, 'sample_meta_data_df.rds'))
  
} else {
  sample_meta_data <- readRDS(file.path(meta_data.dir, 'sample_meta_data_df.rds'))
}

```

# import_data
## load_tximeta_obj
```{r}
import::from(.directory = r_code.dir, 
             .from = 'helper_analysisFunctions.R', 
             load.tximeta.object.list,
             parse.tximeta.quant.metadata)

salmon_quant <- load.tximeta.object.list('salmon', 
                                         output_data.dir = output_data.dir)

salmon_quant <- parse.tximeta.quant.metadata(salmon_quant)

ucsc.rmsk.salmon_quant <- load.tximeta.object.list('ucsc.rmsk.salmon', 
                                                   output_data.dir = output_data.dir)

ucsc.rmsk.salmon_quant <- parse.tximeta.quant.metadata(ucsc.rmsk.salmon_quant)

process.aware.salmon_quant <- load.tximeta.object.list('process.aware.salmon', 
                                                       output_data.dir = output_data.dir)

process.aware.salmon_quant <- parse.tximeta.quant.metadata(process.aware.salmon_quant)
```

# analysis_INTERACTIVE
## QC_filter
```{r}
import::from(.directory = r_code.dir, 
             .from = 'helper_analysisFunctions.R', 
             subset.tximeta.se)

qc_fails <- c('panc.6.2.5', 'panc.7.2.5', 'panc.9.2.5', 
              'panc.10.2.5', 'covid.427.0.80', 'covid.381.0.80')

salmon_quant$bioIvt_panc_salmon <- 
  subset.tximeta.se(salmon_quant$bioIvt_panc_salmon, 
                    filter_list = qc_fails)

ucsc.rmsk.salmon_quant$bioIvt_panc_ucsc.rmsk.salmon <- 
  subset.tximeta.se(ucsc.rmsk.salmon_quant$bioIvt_panc_ucsc.rmsk.salmon, 
                    filter_list = qc_fails)

process.aware.salmon_quant$bioIvt_panc_process.aware.salmon <- 
  subset.tximeta.se(process.aware.salmon_quant$bioIvt_panc_process.aware.salmon, 
                    filter_list = qc_fails)

##

salmon_quant$bioIvt_covid_salmon <- 
  subset.tximeta.se(salmon_quant$bioIvt_covid_salmon, 
                    filter_list = qc_fails)

ucsc.rmsk.salmon_quant$bioIvt_covid_ucsc.rmsk.salmon <- 
  subset.tximeta.se(ucsc.rmsk.salmon_quant$bioIvt_covid_ucsc.rmsk.salmon, 
                    filter_list = qc_fails)

process.aware.salmon_quant$bioIvt_covid_process.aware.salmon <- 
  subset.tximeta.se(process.aware.salmon_quant$bioIvt_covid_process.aware.salmon, 
                    filter_list = qc_fails)


```

## construct_analysis_sets
```{r}
import::from(.directory = r_code.dir, 
             .from = 'helper_analysisFunctions.R', 
             build.analysis.set)
##
salmon_quant$analysis_set$panc_ctrl <- 
  build.analysis.set(se_list = salmon_quant, 
                     se_1 = 'bioIvt_panc_salmon', 
                     se_2 = 'pittsburgh_ctrl_salmon',
                     sample_meta_in = sample_meta_data$`2022.01.14_bioIVTAndPitts_meta_data.csv`)

salmon_quant$analysis_set$covid_ctrl <- 
  build.analysis.set(se_list = salmon_quant, 
                     se_1 = 'bioIvt_covid_salmon', 
                     se_2 = 'pittsburgh_ctrl_salmon',
                     sample_meta_in = sample_meta_data$`2022.01.14_combined_meta_data.csv`)

salmon_quant$analysis_set$ctrl_panc_covid <- 
  build.analysis.set(se_list = salmon_quant, 
                     se_1 = 'bioIvt_panc_salmon', 
                     analysis_set_2 = salmon_quant$analysis_set$covid_ctrl,
                     sample_meta_in = sample_meta_data$`2022.01.14_combined_meta_data.csv`)
##
ucsc.rmsk.salmon_quant$analysis_set$panc_ctrl <- 
    build.analysis.set(se_list = ucsc.rmsk.salmon_quant, 
                       se_1 = 'bioIvt_panc_ucsc.rmsk.salmon', 
                       se_2 = 'pittsburgh_ctrl_ucsc.rmsk.salmon',
                       sample_meta_in = sample_meta_data$`2022.01.14_bioIVTAndPitts_meta_data.csv`)

ucsc.rmsk.salmon_quant$analysis_set$covid_ctrl <- 
    build.analysis.set(se_list = ucsc.rmsk.salmon_quant, 
                       se_1 = 'bioIvt_covid_ucsc.rmsk.salmon', 
                       se_2 = 'pittsburgh_ctrl_ucsc.rmsk.salmon',
                       sample_meta_in = sample_meta_data$`2022.01.14_combined_meta_data.csv`)

ucsc.rmsk.salmon_quant$analysis_set$ctrl_panc_covid <- 
    build.analysis.set(se_list = ucsc.rmsk.salmon_quant, 
                       se_1 = 'bioIvt_panc_ucsc.rmsk.salmon', 
                       analysis_set_2 = ucsc.rmsk.salmon_quant$analysis_set$covid_ctrl,
                       sample_meta_in = sample_meta_data$`2022.01.14_combined_meta_data.csv`)
##
process.aware.salmon_quant$analysis_set$panc_ctrl <- 
    build.analysis.set(se_list = process.aware.salmon_quant, 
                       se_1 = 'bioIvt_panc_process.aware.salmon', 
                       se_2 = 'pittsburgh_ctrl_process.aware.salmon',
                       sample_meta_in = sample_meta_data$`2022.01.14_bioIVTAndPitts_meta_data.csv`)

process.aware.salmon_quant$analysis_set$covid_ctrl <- 
    build.analysis.set(se_list = process.aware.salmon_quant, 
                       se_1 = 'bioIvt_covid_process.aware.salmon', 
                       se_2 = 'pittsburgh_ctrl_process.aware.salmon',
                       sample_meta_in = sample_meta_data$`2022.01.14_combined_meta_data.csv`)

process.aware.salmon_quant$analysis_set$ctrl_panc_covid <- 
    build.analysis.set(se_list = process.aware.salmon_quant, 
                       se_1 = 'bioIvt_panc_process.aware.salmon', 
                       analysis_set_2 = process.aware.salmon_quant$analysis_set$covid_ctrl,
                       sample_meta_in = sample_meta_data$`2022.01.14_combined_meta_data.csv`)
```

## generate_filters_and_normalized_counts
```{r}

import::from(.from = 'SummarizedExperiment', colData, assay, rowRanges, assays)
import::from(.from = 'DESeq2', .all = T)

if(! "apeglm" %in% rownames(installed.packages())) { 
    BiocManager::install('apeglm', update = FALSE)
}

type <- 'gxi'
base_level <- 'ctrl'
input_se <- salmon_quant$analysis_set$ctrl_panc_covid 
dds_formula <- as.formula(~age+input_vol+condition)

scaled_quant_meta_for_de.df <- 
  input_se$quant_meta %>% 
    mutate(input_vol = as.numeric(input_vol),
           condition = relevel(as.factor(condition), ref = base_level)) %>% 
    mutate_if(is.numeric, ~scale(., center = T)) %>% 
    mutate_if(is.character, ~as.factor(.))

print(levels(scaled_quant_meta_for_de.df$condition))

gencode_sex_filter.df <-
  rowRanges(input_se[[type]]) %>% as.data.frame() %>% 
  filter(seqnames %in% c('chrY'))
  # filter(seqnames %in% c('chrY'),
  #        grepl('ENSG', group_name))

count_matrix.df <- 
  assay(input_se[[type]], 'counts') %>% 
  as.data.frame() %>% 
  rownames_to_column('gene') %>% 
  mutate_if(is.numeric, round) %>% 
  column_to_rownames('gene')

input_set_dds <- DESeqDataSetFromMatrix(countData = count_matrix.df, 
                                        colData = scaled_quant_meta_for_de.df, 
                                        design = dds_formula)

input_set_dds <- estimateSizeFactors(input_set_dds)

input_set_dds_norm_counts.df <- as.data.frame(counts(input_set_dds, normalized=T))

condition_aware_age_cor_filter <- 
  input_set_dds_norm_counts.df %>% 
    rownames_to_column('ensg') %>% 
    gather(sample, count, -ensg) %>% 
    merge(input_se$quant_meta %>% select(sample, age, condition), by = 'sample') %>% 
    group_by(condition, ensg) %>% 
    summarize(age_cor = cor(count, age, method = 'pearson')) %>% 
    drop_na() %>% 
    filter(abs(age_cor) >= 0.70) %>% 
    spread(condition, age_cor)

# condition_aware_input_vol_cor_filter <- 
#   input_set_dds_norm_counts.df %>% 
#     rownames_to_column('ensg') %>% 
#     gather(sample, count, -ensg) %>% 
#     merge(input_se$quant_meta %>% select(sample, input_vol, condition), by = 'sample') %>% head()
#     group_by(condition, ensg) %>% 
#     summarize(input_vol_cor = cor(count, input_vol, method = 'pearson')) %>% 
#     drop_na() %>% 
#     filter(abs(input_vol_cor) >= 0.70) %>% 
#     spread(condition, input_vol_cor)

input_set_dds_vst_counts <-  as.data.frame(assay(vst(input_set_dds, blind = F)))

input_set_dds_vst_counts[! rownames(input_set_dds_vst_counts) %in% 
                           c(condition_aware_age_cor_filter$ensg,
                             gencode_sex_filter.df$gene_id), ] %>% t() -> pca_tmp_in 
  
pca_tmp_in_sd <- apply(pca_tmp_in, 2, sd)
pca_tmp_in_zero_sd <- pca_tmp_in[,pca_tmp_in_sd!=0]
non_zero_pca <- prcomp(pca_tmp_in_zero_sd, center = T, scale. = T, rank. = 50)

summary(non_zero_pca)
pcs.of.interest <- apply(non_zero_pca$x, 2, var)
pcs.props <-  pcs.of.interest/sum(pcs.of.interest)
cumsum(pcs.props)[c(1,2)]
print(as.data.frame(pcs.props) %>% 
  rownames_to_column('pc') %>% 
  mutate(pc = as.numeric(sub('PC', '', pc))) %>% 
  ggplot(aes(pc, pcs.props)) + 
  geom_col())

pca.out <- as.data.frame(non_zero_pca$x) %>% 
  rownames_to_column('sample') %>% 
  merge(scaled_quant_meta_for_de.df, by = 'sample')

pca.out.summary <- 
  as.data.frame(summary(non_zero_pca)$importance) %>% 
  rownames_to_column('metric') %>% 
  gather(pc, value, -metric) %>% 
  spread(metric, value)

pca.out %>% 
  ggplot(aes(PC1, PC2,
             color = condition)) +
  geom_point(size = rel(2), alpha = 0.8) + 
  xlab(paste('PC1', round(cumsum(pcs.props)[1], digits = 3), sep = ' ')) +
  ylab(paste('PC2', round(cumsum(pcs.props)[2] - cumsum(pcs.props)[1], digits = 3), sep = ' ')) +
  geom_vline(xintercept = 0, linetype = 'dotted', alpha = 0.3, size = 0.25) +
  geom_hline(yintercept = 0, linetype = 'dotted', alpha = 0.3, size = 0.25) + 
  # scale_color_manual(values = identity_color_pal)
  scale_color_viridis_d()

pca.out %>% 
  ggplot(aes(PC2, PC3,
             color = condition)) +
  geom_point(size = rel(2), alpha = 0.8) + 
  xlab(paste('PC2', round(cumsum(pcs.props)[2] - cumsum(pcs.props)[1], digits = 3), sep = ' ')) +
  ylab(paste('PC3', round(cumsum(pcs.props)[3] - cumsum(pcs.props)[2], digits = 3), sep = ' ')) +
  geom_vline(xintercept = 0, linetype = 'dotted', alpha = 0.3, size = 0.25) +
  geom_hline(yintercept = 0, linetype = 'dotted', alpha = 0.3, size = 0.25) + 
  scale_color_manual(values = identity_color_pal)


Filter(function(x) sd(x) !=0, pca.out %>% select(where(is.numeric))) %>% 
  # filter(primary_diagnosis %in% c(' ', 'Pancreatic')) %>% 
  cor(method = 'spearman') %>% 
  as.data.frame() %>% 
  select(-starts_with('PC')) %>% 
  rownames_to_column('pc') %>% 
  filter(grepl('^PC', pc)) %>% 
  gather(var, cor, -pc) %>% 
  mutate(pc = as.factor(as.numeric(str_remove(pc, 'PC')))) %>% 
  filter(pc %in% c(1,2,3)) %>% 
  ggplot(aes(pc, cor, label = var)) + 
  geom_boxplot(fill = NA, outlier.colour = NA) + 
  geom_point(alpha = 0.5) +
  ggrepel::geom_text_repel(aes(label = ifelse(abs(cor) >= 0.70 & grepl('percent|splice', var), 
                                              paste0(var,'_', round(cor, 3)), ''))) +
  ylim(-1,1) + ylab('pearson correlation')


de_filter <- rowSums(counts(input_set_dds, normalized=T) >= 10) >= ncol(input_set_dds_norm_counts)*0.75

input_set_dds <- DESeq(input_set_dds[de_filter,])

print(resultsNames(input_set_dds))

tail(resultsNames(input_set_dds), n=2)

coef_list <- tail(resultsNames(input_set_dds), n=2)

covid_vs_ctrl <- 
  lfcShrink(input_set_dds, coef = coef_list[[1]]) %>% 
  as.data.frame() %>% 
  rownames_to_column('ensg') %>% 
  filter(!ensg %in% c(condition_aware_age_cor_filter$ensg,
                             sex_filter$gene_id))
#%>%
  merge(rowRanges(input_se[[type]]) %>% as.data.frame(), by.x = 'ensg', by.y = 'gene_id') %>% 
  merge(reference_meta_data$total_tx_to_gene.df %>% select(ensg, gene) %>% distinct(), by = 'ensg')

panc_vs_ctrl <- 
  lfcShrink(input_set_dds, coef = coef_list[[2]]) %>% 
  as.data.frame() %>% 
  rownames_to_column('ensg') %>% 
  filter(!ensg %in% c(condition_aware_age_cor_filter$ensg,
                             sex_filter$gene_id)) 
#%>% 
  merge(rowRanges(input_se[[type]]) %>% as.data.frame(), by.x = 'ensg', by.y = 'gene_id') %>% 
  merge(reference_meta_data$total_tx_to_gene.df %>% select(ensg, gene) %>% distinct(), by = 'ensg')

plotMA(lfcShrink(input_set_dds, coef = 4))

coef(input_set_dds) %>% as.data.frame() -> tmp_df


boxplot(log10(assays(input_set_dds)[["cooks"]]), range=0, las=2)


```

## compare_samples_w_nanopore
```{r}
panc.7.1.1_nanopore_tpm <- read_tsv(file.path(output_data.dir, 'nanopore', 'gencodev39', 'panc.7.1.1_gene_abundance.tsv'))
panc.6.1.1_nanopore_tpm <- read_tsv(file.path(output_data.dir, 'nanopore', 'gencodev39', 'panc.6.1.1_gene_abundance.tsv'))


input_set_dds_norm_counts.df[, 'panc.7.1.1', drop = F] %>% rownames_to_column('Gene ID') %>% 
  merge(panc.7.1.1_nanopore_tpm, by = 'Gene ID') %>% 
  dplyr::rename('nanopore_tpm' = TPM) %>% 
  mutate(illumina_tpm = panc.7.1.1*1e6/(sum(panc.7.1.1))) -> panc.7.1.1_seq_compare.df

input_set_dds_norm_counts.df[, 'panc.6.1.1', drop = F] %>% rownames_to_column('Gene ID') %>% 
  merge(panc.6.1.1_nanopore_tpm, by = 'Gene ID') %>% 
  dplyr::rename('nanopore_tpm' = TPM) %>% 
  mutate(illumina_tpm = panc.6.1.1*1e6/(sum(panc.6.1.1))) -> panc.6.1.1_seq_compare.df


panc.7.1.1_seq_compare.df %>% 
  filter(illumina_tpm > 1 & nanopore_tpm > 1) %>% 
  ggplot(aes(log2(illumina_tpm + 1), log2(nanopore_tpm + 1), label = `Gene ID`)) + 
  geom_point(alpha = 0.4)

panc.6.1.1_seq_compare.df %>% 
  filter(illumina_tpm > 1 & nanopore_tpm > 1) %>% 
  ggplot(aes(log2(illumina_tpm + 1), log2(nanopore_tpm + 1), label = `Gene ID`)) + 
  geom_point(alpha = 0.4) 


count_matrix.df[, 'panc.7.1.1', drop = F] %>% rownames_to_column('Gene ID') %>% 
  mutate(panc.7.1.1_tpm = panc.7.1.1*1e6/(sum(panc.7.1.1))) %>% 
  merge(panc.7.1.1_nanopore_tpm %>% select(`Gene ID`, TPM), by = 'Gene ID') %>% 
  dplyr::rename('panc.7.1.1_nanopore_tpm' = TPM) %>% 
  merge(count_matrix.df[, 'panc.6.1.1', drop = F] %>% rownames_to_column('Gene ID') %>% 
        mutate(panc.6.1.1_tpm = panc.6.1.1 *1e6/(sum(panc.6.1.1))) %>% 
            merge(panc.6.1.1_nanopore_tpm %>% select(`Gene ID`, TPM), by = 'Gene ID') %>% 
            dplyr::rename('panc.6.1.1_nanopore_tpm' = TPM), by = 'Gene ID') -> panc_compare.df

panc_compare.df %>% 
  # filter_if(is.numeric, ~. > 1) %>% 
  # ggplot(aes(log2(ctrl.10.0.4_tpm + 1), log2(panc.7.1.1_tpm + 1))) + 
  ggplot(aes(panc.6.1.1_tpm, panc.7.1.1_tpm)) + 
  geom_point(alpha = 0.4) -> plt.1

panc_compare.df %>% 
  # filter_if(is.numeric, ~. > 1) %>% 
  ggplot(aes(log2(panc.6.1.1_nanopore_tpm + 1), log2(panc.7.1.1_nanopore_tpm + 1))) + 
  geom_point(alpha = 0.4) -> plt.2

panc_compare.df %>% 
  # filter_if(is.numeric, ~. > 1) %>% 
  ggplot(aes(log2(panc.6.1.1_nanopore_tpm + 1), log2(ctrl.10.0.4_tpm + 1))) + 
  geom_point(alpha = 0.4) -> plt.3

panc_compare.df %>% 
  # filter_if(is.numeric, ~. > 1) %>% 
  ggplot(aes(log2(panc.7.1.1_nanopore_tpm + 1), log2(panc.7.1.1_tpm + 1))) + 
  geom_point(alpha = 0.4) -> plt.4

plt.1 + plt.3 / plt.4 + plt.2


```


